import React from 'react';
import { AdScenario } from '../types';

interface ScenarioViewProps {
  scenario: AdScenario;
}

const ScenarioView: React.FC<ScenarioViewProps> = ({ scenario }) => {
  const downloadScenario = () => {
    const content = `
캠페인 전략 문서
Generated by Nano Banana Pro
------------------------------------------------
캠페인 제목: ${scenario.title}
마케팅 후킹 메시지: ${scenario.marketingHook}
타겟 오디언스: ${scenario.targetAudience}

컨셉 개요:
${scenario.concept}

------------------------------------------------
이미지 자산 프롬프트 (30개):
${scenario.imagePrompts.map((prompt, index) => `
[자산 #${index + 1}]
${prompt}
`).join('')}
------------------------------------------------
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${scenario.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_strategy.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-zinc-900/50 border border-zinc-800 rounded-2xl p-6 mb-8 animate-fade-in relative">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-yellow-500/10 rounded-lg">
            <svg className="w-6 h-6 text-yellow-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
            </svg>
          </div>
          <h2 className="text-2xl font-bold text-white tracking-tight">최적화된 전략</h2>
        </div>
        
        <button 
          onClick={downloadScenario}
          className="flex items-center gap-2 px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-gray-300 hover:text-white rounded-lg transition-colors border border-zinc-700 text-sm font-medium"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          .txt 다운로드
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div>
          <h3 className="text-yellow-400 text-sm font-semibold uppercase tracking-wider mb-2">캠페인 제목</h3>
          <p className="text-xl text-white font-medium mb-6">{scenario.title}</p>

          <h3 className="text-yellow-400 text-sm font-semibold uppercase tracking-wider mb-2">마케팅 후킹 메시지</h3>
          <p className="text-lg text-gray-300 italic mb-6">"{scenario.marketingHook}"</p>
        </div>
        
        <div>
          <h3 className="text-yellow-400 text-sm font-semibold uppercase tracking-wider mb-2">타겟 오디언스</h3>
          <p className="text-gray-300 mb-6">{scenario.targetAudience}</p>

          <h3 className="text-yellow-400 text-sm font-semibold uppercase tracking-wider mb-2">컨셉</h3>
          <p className="text-gray-300 leading-relaxed">{scenario.concept}</p>
        </div>
      </div>
    </div>
  );
};

export default ScenarioView;